[package]
name = "bigs_id"
version = "0.4.1"
authors = ["henk den bakker"]

[dependencies]
clap = "2.30.0"
bit-vec = "0.5.0"
murmurhash64 = "0.3.1"
fasthash = "0.3.2"
serde = "1.0.27"
serde_json = "1.0.9"
bincode = "0.9.2"
serde_derive = "1.0.27"
flate2 = "1.0.1"
indexmap = "1.0.0"
probability = "0.15.11"
rayon = "1.0.1"
fnv = "1.0.3"
