[package]
name = "bigs_id"
version = "0.1.0"
authors = ["henk"]

[dependencies]
clap = "2.30.0"
simple_bloom = { path = "./simple_bloom" }
kmer_fa = { path = "./kmer_fa" }
bit-vec = "0.4.3"
murmurhash64 = "0.3.1"
serde = "1.0.27"
serde_json = "1.0.9"
bincode = "0.9.2"
serde_derive = "1.0.27"
flate2 = "1.0.1"
